### ISSUE TITLE
UDP version of CHARGEN doesn't work

### ISSUE THREAD

**Issue by nebooben** [radek-dab/chargen#2]
Output for `nc -u localhost 19` is empty.
TCP version works fine for `nc localhost 19`

**Comment by radek-dab** [comment]
From RFC 864:

> A server listens for UDP datagrams on UDP port 19.  When a datagram is received, an answering datagram is sent containing a random number (between 0 and 512) of characters (the data in the received datagram is ignored).

So you have to send some data to receive an answer. For example:

```
$ nc -u localhost 19
test
!"#$%&'()*+,-./0123456789:;<=>?@ABC
udp
!"#$%&'()*+,-./0123456789:;<=>
chargen
!"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefgh
"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghi
#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghij
$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijk
%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijkl
&'()*+,-./0123456789:;<=>?@ABCDEFGHIJ
```

**Comment by nebooben** [comment]
Thank you, it helps!
